name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Installe Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      # Installe les dépendances avec Bun
      - run: bun install

      # Build avec Bun
      - run: npm run build

      # Tests avec Bun et npm (optionnel)
      - run: bun test
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      # Installe Bun ici aussi (pour rebuild avant publish si nécessaire)
      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: npm run build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
